### ISSUE TITLE
Remove (or reduce) dependency on Swiftz

### ISSUE THREAD

**Issue by gfontenot** [typelift/SwiftCheck#100]
I'd love to use SwiftCheck to do the property based testing for [Runes](https://github.com/thoughtbot/Runes). However, since both Runes and Swiftz define (slightly different) operators for `map`, I'm not able to. This is a bummer, since it seems like Swiftz is an internal dependency of SwiftCheck, and this is one place where that dependency is leaking out.

I filed a radar (22676864) about this same issue on Apple's side after [a conversation with Joe Groff](https://twitter.com/GFontenot/status/643070699553333248), but it also seems like it can be mitigated by reducing the dependency on Swiftz to what is absolutely necessary. In this case, by not pulling the operator definitions (which don't _appear_ to be used in SwiftCheck, based on my search results) into SwiftCheck, both of our libraries would play nicely together.

**Comment by CodaFi** [comment]
The latest release completely removes any dependence on Swiftz.

**Comment by CodaFi** [comment]
The problems you have aren't with Swiftz, they're with our new framework Operadics.  And given that Seift doesn't play nicely with non-identical definitions of the same operator in the same compilation unit that's where your errors are coming from (they seem to have gotten worse in the GM, no?). In order to resolve these conflicts you need to specifically import symbols one or the other framework that you're testing in that particular case to avoid the operator clashing.

**Comment by gfontenot** [comment]
Ah, my bad. I skimmed and made an assumption.

Unfortunately, importing specific symbols doesn't work for operator definitions (it would only work for operator definitions).

Regardless, it feels off to run into problems like this for code that isn't ever used. None of the operators defined in Runes are used in SwiftCheck, but their inclusion in Operadics (and so their implicit inclusion in SwiftCheck) means that we have (as far as I can tell) an unreconcilable conflict.

**Comment by CodaFi** [comment]
What do you mean you can't conditionally import symbols?  The least you need from us should be

```swift
// import XCTest
// import Quick
import func SwiftCheck.property
import func SwiftCheck.<-
import func SwiftCheck.forAll
```

**Comment by gfontenot** [comment]
yep, I can do that, but that doesn't prevent Xcode from finding the operator definition itself. Our precedences are different, so it causes a conflict.

You can see this yourself by pulling down the `gf-swiftcheck` branch here: https://github.com/thoughtbot/Runes/tree/gf-swiftcheck

**Comment by CodaFi** [comment]
Ah, that's definitely a regression.

```swift
import func SwiftCheck.*
```

seems to bring all operators into scope no matter what...

Tho it may be a hack, I can produce an operadics-free branch just for this kind of case until Swift gets its act together.

**Comment by CodaFi** [comment]
Or the alternative may be to just update Operadics to run with your precedences.  You seem to have thought about them quite a bit more than we have.

**Comment by CodaFi** [comment]
Updated.

Literally all you have to do to your cartfile is peg master instead of `0.3.0` and your tests compile and run without a single change.

**Comment by gfontenot** [comment]
Yep, confirmed. I appreciate the accommodation. Bummer that we needed source changes to make everything play nice together :disappointed:

**Comment by CodaFi** [comment]
Agreed. 

Closing this for now.  I'll try to put out a proper release soon if Swift 2.0 doesn't manage to get around to this one.
