### ISSUE TITLE
Case causes Xcode to crash

### ISSUE THREAD

**Issue by zbeckman** [typelift/SwiftCheck#101]
The following property is causing Xcode to crash (latest pull from `master` and using Xcode 7 GM):
```
property("generates arbitrary Int") <- forAll(Gen<Int>.choose((Int.min, Int.max))) { (i: Int) in
	return i >= Int.min && i <= Int.max
}
```
It looks like a `BAD_INSTRUCTION` but Xcode crashes quickly, so I only have an instant to see it.

**Comment by CodaFi** [comment]
Got a stack trace?

**Comment by zbeckman** [comment]
Nope – It dies too fast. Unless you are aware of a place on disk where I might be able to find one after Xcode crashes?

**Comment by CodaFi** [comment]
If Xcode itself gets taken down you should always have something in ~/Library/Logs/CrashReporter

**Comment by zbeckman** [comment]
Nope, nothing there... alas.

**Comment by CodaFi** [comment]
Hmph.  This would make for a fascinating bug report.

**Comment by CodaFi** [comment]
Try using the new `Large` modifier for now.

**Comment by CodaFi** [comment]
Did you ever find a way to make this work?

**Comment by CodaFi** [comment]
It's been a month and a half and I haven't heard anything from you.  I'm closing this due to age.  Pull the latest tags and, if this issue persists, open a new issue with more information.

Thanks! :sparkles:
