### ISSUE TITLE
Strange log output "falsifiable" even though tests pass

### ISSUE THREAD

**Issue by zbeckman** [typelift/SwiftCheck#102]
This test:
```
let p = CheckerArguments(replay: Optional.Some((standardRNG, 10)), maxAllowableSuccessfulTests: 100, maxAllowableDiscardedTests: 100, maxTestCaseSize: 1000)
					
property("does not generate negatives", arguments: p) <- forAll(Gen<UInt>.choose((0, 1000000))) { (i: UInt) in
	return i < 0
}.expectFailure
```
Generates this log output:
```
Test Case '-[GlimpulseTests.TestGenerators SwiftCheck__testing_basic_generators__changes_the_property_parameters_UserszbeckmanProjectsGlimpulseiOSprojectGlimpulseGlimpulseTestsTestGeneratorsswift_116]' started.
+++ OK, failed as expected. Proposition: does not generate negatives
Falsifiable (after 1 test and 20 shrinks):
0
```
The test does pass – but it's confusing to see what *looks like* a failure in the output. Clearly, it's not actually a falsifiable test with the value zero, but the output shows that it is...

**Comment by CodaFi** [comment]
Of course it's falsifiable, it just failed!  The +++ is supposed to be an indicator that it was expected.

**Comment by zbeckman** [comment]
I understand that – I'm just saying the way the log output is written, it is confusing. Perhaps change the word "Falsifiable" to "Expected falsifiable?" The other part that is confusing is that it emits "0" in the logs, which sounds like the false property is "return 0 < 0" which... is not true.

So again – yes, I get it – I'm just talking about how the log output is very confusing as it is written.

**Comment by CodaFi** [comment]
I believe it's output that way because failure and the expectations mechanism are two different subsystems reacting to 2 different events.  If you want to have a crack at improving it check out the bottom of `Test.swift`.

**Comment by CodaFi** [comment]
(`0` is most certainly a failing case because !(a < b) ≡ (a >= b)

**Comment by CodaFi** [comment]
Closing as: behaves as expected + lack of activity.
