### ISSUE TITLE
CheckerArgument for minTests

### ISSUE THREAD

**Issue by zbeckman** [typelift/SwiftCheck#103]
Is it possible to use `CheckerArguments` to specify a minimum number of positive tests? I've been playing with it, e.g,
```
CheckerArguments(replay: Optional.Some((standardRNG, 10)), maxAllowableSuccessfulTests: 200, maxAllowableDiscardedTests: 100, maxTestCaseSize: 1000)
```
It seems we have control of the *maximum* parameters, but not minimum.

But the most common need we have is to *increase* the number of tests from 100. For example, we have some patterns that require a pretty wide range of testing before we can be "reasonably certain" that all conditions are passed. We'd like to be able to specify 1,000 test cases for these.

Other situations in which having more than 100 passing test cases make sense:

1. Performance. Quite often we need to run more than 100 cases in order to obtain a reasonable baseline on performance checking.
2. Volume oriented testing. For instance, does the database create 10,000 records without failing?
3. Large data sets. Already mentioned: Situations where failure is only detectable on the order of 1 in a 1,000 cases.

**Comment by CodaFi** [comment]
Perhaps "max" is the wrong word here.  "Max" as in "ceiling" (what you mean) not max as in "testing can possibly reach this amount".

**Comment by zbeckman** [comment]
Right. If it's possible to introduce a `minTests` or `minPassingTests` or something that would meet the need... The various *max* parameters are well-named and clear.

**Comment by CodaFi** [comment]
But that's what I'm saying: your definition of "min" and the current use of "max" are semantically the same.  SwiftCheck doesn't have a "min" or "max" concept when testing, it just has a set of constants that tell it when to stop testing.  I'm saying the parameters to the checker arguments might be named poorly if this is the kind of mix-up you're having.

**Comment by CodaFi** [comment]
"limit" is a better noun.

**Comment by zbeckman** [comment]
Hmm. Ok, I think I see the issue... Based on the current nouns, it seems they don't support what I want and I jump to the question of additional functionality – "it sure would be nice if I could do this other thing which isn't supported by these parameters." But it sounds like the architecture won't really support the "other thing," that being: "Run at least X tests, successfully, no matter what, where I can specify what X is." (I was trying to build a configuration with 1,000 tests minimum, but it would routinely conclude success with a much smaller set of test runs).

**Comment by CodaFi** [comment]
That seems like an odd thing to have in a framework built around the `∀` quantifier.

**Comment by zbeckman** [comment]
Fancy words again. ;)

**Comment by zbeckman** [comment]
(And yes – I kind of agree with you – except, when the rubber meets the road, and a QA team is putting this tool to use to build "real world" cases. Of course, it can be done with a loop, but I like patterns. I like to glance through the test cases and say "aha! You didn't use a property! Bad bad!")

**Comment by CodaFi** [comment]
Because arguments already do the thing you want, I think what you're asking for are global options to the testing loop in addition to this.  That is something both frameworks haven't figured out how to do yet.

**Comment by CodaFi** [comment]
OK, this issue has gone a month without any updates.  If you're still having this problem feel free to lodge another.

Closing this.
