### ISSUE TITLE
Tests cases that throw exceptions don't print the counterexample

### ISSUE THREAD

**Issue by kballard** [typelift/SwiftCheck#115]
When SwiftCheck catches an error thrown by a test case, it prints the error, but it doesn't print the counterexample. This means I have no idea what input caused the problem.

**Comment by CodaFi** [comment]
Oh dear.  Give me just a minute to close out the other pull request and I'll have one where we can amend this together.

**Comment by kballard** [comment]
I found the code responsible, I'll toss you a PR.
