### ISSUE TITLE
ComplexSpec.swift testIPv6Properties generates identical examples for a test run

### ISSUE THREAD

**Issue by MichaelShaw** [typelift/SwiftCheck#131]
The e-mail example "testEmailAddressProperties()" in the same file works fine. 

The IP example "testIPv6Properties()" will generate 100 examples of the same input for each test run, this can be checked by adding a simple print.

**Comment by CodaFi** [comment]
Hi, thanks for the the report!

Are you using the latest SwiftCheck?  I just patched an issue similar to this in v0.4.0.

**Comment by MichaelShaw** [comment]
I've been installing using CocoaPods, from my lock file "- SwiftCheck (0.4.0)", installed yesterday.

I'm familiar with property testing, but relatively new to Swift, so forgive me if I'm mistaken. I'm getting the same problem with a simpler case of fromElementsIn (copy & pasted from the problematic example), this generates the same character for the entire test run. 

```
        let numeric : Gen<Character> = Gen<Character>.fromElementsIn("0"..."9")
        property("test numeric") <- forAll(numeric) { n in
            print("n is \(n)")
            return true
        }
```

**Comment by MichaelShaw** [comment]
Unless I'm missing something, the current master branch is missing Operators.swift that the project expects, so I can't build.

**Comment by pthariensflame** [comment]
@MichaelShaw You need to pull in all the submodules as well.

**Comment by mpurland** [comment]
```git submodule update --init --recursive``` should do the trick

**Comment by CodaFi** [comment]
Oops, typo.  I meant v0.4.1.  That would explain the behavior you're seeing.

**Comment by mpurland** [comment]
It looks like he's using CocoaPods. It looks like 0.4.1 isn't in CocoaPods repository yet.

```
> pod search swiftcheck

-> SwiftCheck (0.4.0)
   QuickCheck for Swift.
   pod 'SwiftCheck', '~> 0.4.0'
   - Homepage: https://github.com/typelift/SwiftCheck
   - Source:   https://github.com/typelift/SwiftCheck.git
   - Versions: 0.4.0, 0.3.2, 0.3.0, 0.2.6 [master repo]
```

**Comment by CodaFi** [comment]
I don't remember why I didn't want to release 0.4.1 as a spec, but I'll do that now.

**Comment by MichaelShaw** [comment]
Thanks for the help on how to build it. The problem is gone in the latest version.

**Comment by CodaFi** [comment]
@MichaelShaw Thank you for reporting this issue.  If you have any more or questions, comments, whatever, we're always happy to hear about it!

:sparkles:
