### ISSUE TITLE
What's the impact of SE-0002 (Removing currying `func` declaration syntax)?

### ISSUE THREAD

**Issue by kykim** [typelift/SwiftCheck#139]
https://github.com/apple/swift-evolution/blob/master/proposals/0002-remove-currying.md
I'm assuming this will be implemented in Swift 3.

Just curious if this has any impact at all.
Looking at the `Tutorial.xcplayground`, I'm guessing this function:
```
// Concatenates 5 strings together in order.
func glue5(l : String)(m : String)(m2 : String)(m3 : String)(r : String) -> String {
	return l + m + m2 + m3 + r
}
```
would need to be altered to something like this (?):
```
func glue5a(l: String) -> (String) -> (String) -> (String) -> (String) -> String {
    return { (m: String) -> (String) -> (String) -> (String) -> String in
            { (m2: String) -> (String) -> (String) -> String in
                { (m3: String) -> (String) -> String in
                    { (r: String) -> String in
                        return l + m + m2 + m3 + r
                    }
                }
            }
    }
}
```
Ugh.

**Comment by CodaFi** [comment]
Hm, yeah. Should probably rewrite that example when the time rolls around.  I'm not satisfied with the explanation I have for the monad-et-al combinators, and there's no section on reply support.

**Comment by mpurland** [comment]
With function currying syntax being removed I hope optimizations around manual function currying with closures is added.

**Comment by CodaFi** [comment]
I've got it! [Problem solved](https://github.com/CodaFi/SwiftCheck/commit/c08eee11122abd1fea9e316e0411582f674c2720#diff-47970fd31917fb63ccf81bd68065f0abR275).
