### ISSUE TITLE
Carthage can’t build SwiftCheck-iOS scheme 

### ISSUE THREAD

**Issue by samritchie** [typelift/SwiftCheck#146]
It looks like the SwiftCheck-iOS scheme has the test target configured to build for the Analyze & Run actions. This causes build failures in carthage - “error: module 'SwiftCheck' was not compiled for testing”

**Comment by CodaFi** [comment]
Well that's annoying.  Can you flip the `Enable Testability` switch in the target in a pull request please?

**Comment by ikesyo** [comment]
This sould be the same as https://github.com/typelift/Swiftz/pull/289.

**Comment by samritchie** [comment]
Opened PR #147

**Comment by CodaFi** [comment]
[And we're live](https://github.com/typelift/SwiftCheck/releases/tag/v0.5.1).

Thanks again!  :heart:
