### ISSUE TITLE
Int64.randomInRange crashes with multiplication overflow

### ISSUE THREAD

**Issue by mayoff** [typelift/SwiftCheck#151]
Test case:

    Int64.randomInRange((1 << 49, 1 << 56), gen: StdGen(1 << 49, 1 << 56))

Crashes on this line in `Int64.randomInRange`:

			let magtgt = k * q

with k = 71494644084506625, q = 1000.

**Comment by mayoff** [comment]
Also crashes:

    Gen<Int64>.choose((Int64.min, -1)).generate

On the addition in this line:

			let k = Int64.subtractWithOverflow(h, l).0 + 1

**Comment by CodaFi** [comment]
I ran into this myself while updating for 2.2.  Can you see if the patch in [this pull request](https://github.com/CodaFi/SwiftCheck/blob/work-stealing/Sources/Random.swift) does it for you?  If so I can push a minor release.

**Comment by CodaFi** [comment]
No, wait, that fixes nothing.  I fear I need a new algorithm that tolerates integer overflow better than this crude port.

**Comment by CodaFi** [comment]
OK, I have a terrible hack that I closes the cases you mention here by shunting up and down between Int64 and Double for extended precision types.  Theoretically, this adds a bit more entropy on top of the regular generator as an added bonus, but it makes me uncomfortable...

**Comment by CodaFi** [comment]
I believe I have a tentative fix for this now (certainly, it does't crash on the inputs that you've given anymore) in [this patch](https://github.com/typelift/SwiftCheck/pull/150/commits/44ec84b341c3a8697daf961f37c0614398bb5185/).

**Comment by CodaFi** [comment]
If all is good, I will commit this fix to master and push new releases for Swift 2.0-2.1.
