### ISSUE TITLE
Shrinking does not properly work when using choose with a range

### ISSUE THREAD

**Issue by jgongo** [typelift/SwiftCheck#172]
Related with #171 , when using shrinking combined with `choose` with any range, the shrinking process shrinks the value past the range limits, so the returned shrunk value is useless to determine the cause of the failure.

**Comment by jgongo** [comment]
After thinking a bit about this I guess this is a general problem related with any generator not providing values in the whole range of its domain. To be valuable the shrinking process should be limited by the values generated by the generator(s) used in the property definitions, but I guess it would be quite difficult to check if a given (shrunk) value can be generated by a given generator.

The point I'm trying to make is that in this case I don't see the benefit of shrinking the values, as the shrunk value may be out of the valid values for the property, giving no information about why the property failed. I guess the only solution would be to also present the original value unless the shrinking process can be made more intelligent.

**Comment by CodaFi** [comment]
Shrinking should not know about generators.  Please write a [modifier type](https://github.com/typelift/SwiftCheck/blob/master/Sources/Modifiers.swift#L9) to express this.
