### ISSUE TITLE
Can't build with SPM

### ISSUE THREAD

**Issue by adamkuipers** [typelift/SwiftCheck#195]
Version
========

0.7.0

Environment
===========

Mac OS X

Description
============

Can't build with SPM.

Steps To Reproduce
===================

Using the following in Package.swift, run `swift build`.

```swift
import PackageDescription

let package = Package(
    name: "X",
    dependencies: [
      .Package(url: "https://github.com/typelift/SwiftCheck.git",
               majorVersion: 0,
               minor: 7)
    ]
)
```

Expected Result
================

SwiftCheck is fetched and project is built.

Actual Result
==============

Dependency resolution fails with,

```
  % swift package update
Cloning https://github.com/typelift/SwiftCheck.git
HEAD is now at 5dec398 Merge pull request #189 from CodaFi/rental-tux
Resolved version: 0.7.0
error: these referenced modules could not be found: SwiftCheckTests
fix: reference only valid modules
```

**Comment by CodaFi** [comment]
Does deleting your module cache and rebuilding help?  I had some issues checking out repos that retag versions.

**Comment by CodaFi** [comment]
Please rerun `swift build`.
