### ISSUE TITLE
Possible flaw in `Double.shrink` (never ends for property)

### ISSUE THREAD

**Issue by griotspeak** [typelift/SwiftCheck#200]
Version
========

e30300f5d4c212349b5bc01608820e7d810ea457

Environment
===========

macOS 10.12.1 (16B2555)

Description
============

`shrink` will, effectively, never successfully yield an end result for this property.

Steps To Reproduce
===================

``` Swift
reportProperty("odd shrink case") <- forAll { (n : Double) in
    let left = pow(n, 0.5)
    let right = sqrt(n)
    return left == right
}
```

Expected Result
================

In a *not IEEE 754* world, they should be equal. I suspect that floating point tomfoolery means that the property doesn't hold in most cases but regardless of all of that, the testing the property should end in a reasonable amount of time.

Actual Result
==============

The property 'never' finishes testing if it hits a failing case.

**Comment by CodaFi** [comment]
Interestingly it seems QuickCheck itself has [moved on](https://github.com/nick8325/quickcheck/commit/ca74b9f0c7ad504e197146bfae78209ebf57de1f#diff-dbb7ed6c170c91e99ab32effea0a3770R782) from shrinking with an unfold the way I've got it now.  I think that might be the way to go.
