### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by truizlop** [typelift/SwiftCheck#202]
Version
========

0.7.1
git commit hash a687df108322bcd0c54b807dac4771be087e9774

Environment
===========

MacOS X, console application

Description
============
Creating an extension to support `Arbitrary` on an enum results on build errors.

Steps To Reproduce
===================

Create in the code target an enum like this:

```swift
enum Player : String {
    case one = "Player one", two = "Player two"
    
    var other : Player {
        switch(self) {
        case .one: return .two
        case .two: return .one
        }
    }
}
```

In the test target, create an extension to support Arbitrary:

```swift
import XCTest
import SwiftCheck
@testable import TennisKata

extension Player : Arbitrary {
    public static var arbitrary : Gen<Player> {
        return Gen<Player>.fromElementsOf([Player.one, Player.two])
    }
}
```

Expected Result
================
It should compile and build correctly.

Actual Result
==============
```
Undefined symbols for architecture x86_64:
  "type metadata for TennisKata.Player", referenced from:
      static (extension in TennisKataTest):TennisKata.Player.arbitrary.getter : SwiftCheck.Gen<TennisKata.Player> in PlayerTest.o
      type metadata accessor for [TennisKata.Player] in PlayerTest.o
      protocol witness for static SwiftCheck.Arbitrary.shrink (A) -> [A] in conformance TennisKata.Player : SwiftCheck.Arbitrary in TennisKataTest in PlayerTest.o
      l_protocol_conformances in PlayerTest.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Additional Information
==============
I am wondering why the syntax for `Gen<Player>.fromElementsOf([Player.one, Player.two])` is not Swift 3.0, since from what I can see on the repo, it has actually been updated and it should be `Gen<Player>.fromElements(of: [Player.one, Player.two])`. Apparently my project is configured to use Swift 3.0 though.

**Comment by CodaFi** [comment]
This smells like a Swift bug.  If optimizations are enabled for any of the targets involved, what happens if your turn them off?

**Comment by truizlop** [comment]
They were not enabled for Debug and I disabled them for Release; still not working. Are you able to reproduce the bug? Am I using the library correctly? It is the first time I try to use it.

**Comment by truizlop** [comment]
I created this sample project where the issue is isolated so that you can take a look at it - hope it helps
[SwiftCheck-Issue202.zip](https://github.com/typelift/SwiftCheck/files/607159/SwiftCheck-Issue202.zip)

**Comment by CodaFi** [comment]
Ah, wait, this is a command line tool?  You can't import that kind of module without a test host like an enclosing application.  The test is going to run outside of the context of the running application and so it makes sense it wouldn't have access to its symbols.  Try testing a framework target instead.

**Comment by CodaFi** [comment]
Notice, for example, that command line tools like [Carthage][https://github.com/Carthage/Carthage] keep testable logic in `CarthageKit` and test that by linking against it.

**Comment by truizlop** [comment]
Ok, adding the files to the Test target as well solved the issue. Thanks for the hint!
