### ISSUE TITLE
EXC_BAD_ACCESS while generating custom Arbitrary from mapped ArrowOf.arbitrary

### ISSUE THREAD

**Issue by broomburgo** [typelift/SwiftCheck#203]
Hi, I'm running into a problem when I want to create an Arbitrary instance of a struct that has functions in its constructor parameters.

For example, suppose I want to make this struct arbitrary:

```swift
struct Formatter<Value> {
	let lengthLimit: UInt
	let makeString: (Value) -> String

	init(lengthLimit: UInt, makeString: @escaping (Value) -> String) {
		self.lengthLimit = lengthLimit
		self.makeString = makeString
	}

	func format(_ value: Value) -> String {
		let formatted = makeString(value)
		let maxIndex = formatted.index(formatted.startIndex, offsetBy: String.IndexDistance(lengthLimit))
		if maxIndex >= formatted.endIndex {
			return formatted
		} else {
			return formatted.substring(to: maxIndex)
		}
	}
}
```

I need a generator for `UInt` and one for `(Value) -> String`, but because, as of Swift 3, there's no conditional conformance to protocols (for `Formatter` to be arbitrary, `Value` must be coarbitrary), I created another struct like this:

```swift
struct ArbitraryFormatter<Value: CoArbitrary & Hashable>: Arbitrary {
	private let formatter: Formatter<Value>
	init(_ formatter: Formatter<Value>) {
		self.formatter = formatter
	}

	var get: Formatter<Value> {
		return formatter
	}

	static var arbitrary: Gen<ArbitraryFormatter<Value>> {
		return Gen<(UInt,ArrowOf<Value,String>)>
			.zip(UInt.arbitrary, ArrowOf<Value,String>.arbitrary)
			.map { Formatter<Value>(lengthLimit: $0, makeString: $1.getArrow) }
			.map(ArbitraryFormatter.init)
	}
}
```

This seems reasonable to me: the arrow generator is mapped to give an arbitrary function to `Formatter`.

But if I try to run this test:

```Swift
class FormatterTests: XCTestCase {
    
	func testAlwaysCorrectLength() {
		property("Any formatted string is shorter or equal than the provided length") <- forAll { (x: Int, af: ArbitraryFormatter<Int>) in
			let formatter = af.get
			let string = formatter.format(x)
			return string.distance(from: string.startIndex, to: string.endIndex) <= String.IndexDistance(formatter.lengthLimit)
		}
	}
}
```

The test execution crashes due to `attempted to retain deallocated objects`:

![screen shot 2016-11-30 at 15 29 40](https://cloud.githubusercontent.com/assets/939352/20756658/c9cb0602-b713-11e6-81c0-123edc0cddee.png)

The cause seems located here:

![screen shot 2016-11-30 at 15 31 18](https://cloud.githubusercontent.com/assets/939352/20756669/dbba9b8e-b713-11e6-86ba-bbbdf5d8a552.png)

Apparently the instance of `ArrowOfImpl` is gone. It seems like I cannot reliably use the function returned by `getArrow` without the actual `ArrowOf` being strongly referenced somewhere.

Am I doing something wrong? Maybe that mapping is not really sound for SwiftCheck, and in that case I'll find an alternative (my actual use case is a little more complex). Any Ideas?

**Comment by CodaFi** [comment]
You're using everything correctly, it seems I didn't plan for this kind of use case.  I expected all `XXOf` modifiers to only live as long as whatever block they were created in, but unfortunately that seems to prevent composition.  I'll look into stronger ownership semantics here.

**Comment by CodaFi** [comment]
In the meantime you can use the generator definition you have already as a value and construct the block and value alongside the `property` block.

**Comment by broomburgo** [comment]
I guess a possible solution could be to make the closure stored in `arr` to own the table directly, without mentioning `self`, thus something like this:

```swift
convenience init(_ arr : @escaping (T) -> U) {
	var table = Dictionary<T, U>()
	self.init(table, { (_ : T) -> U in return undefined() })
	self.arr = { x in
		if let v = table[x] {
			return v
		}
		let y = arr(x)
		table[x] = y
		return y
	}
}
```

**Comment by CodaFi** [comment]
Done.  Please point any submodules or Package manifests appropriately.

**Comment by broomburgo** [comment]
Great, thanks a lot! I'm currently managing the SwiftCheck dependency through Carthage, are you planning a new release soon?

**Comment by CodaFi** [comment]
Yes, this definitely will have to be a new point-release.  Give me just a moment.
