### ISSUE TITLE
Version 0.7.1 mismatch with readme.md

### ISSUE THREAD

**Issue by bwdowikowski** [typelift/SwiftCheck#209]
The newest version installed by cocoapods is **0.7.1**

According to **readme.md** `Gen<T>` should have method  `fromElements(in:)` but in fact there is only `fromElementsIn()`. 

Which also throws error `No '...' candidates produce the expected contextual result type 'ClosedRange<R>'`
```
let lowercaseChars = Gen<Character>.fromElementsIn("a"..."z") 
```

**Comment by bwdowikowski** [comment]
Officially SwiftCheck is not available in cocoapods.
What's more, if you want to use `ClosedRange<Characters>` in `fromElementsIn` it should looks like
```
let lowercaseChars: Gen<Character> = Gen<Character>.fromElementsIn("a"..."z")
```
But I'm not sure why ilowercaseChars should be explicity `Gen<Character>`.

**Comment by CodaFi** [comment]
Cocoapods broke this repository every time I tried to migrate and push a new version. I'll check this afternoon and try again.

**Comment by CodaFi** [comment]
This explains your confusion too: I recently went through and refactored some prototypes to use labels and updated the README (but not your version in pods).  The README is correct, and the prototype you cite is formally deprecated.

**Comment by bwdowikowski** [comment]
I've switched to Carthage and it is working just fine 👍
