### ISSUE TITLE
Carthage build cache is always invalid for SwiftCheck

### ISSUE THREAD

**Issue by broomburgo** [typelift/SwiftCheck#217]
Hi, I'm experiencing some annoying behavior with SwiftCheck and Carthage: the latter did recently introduce the option to cache builds (i.e. don't rebuild dependencies which were already built for a certain version during an update) but for some reason SwiftCheck always rebuilds after an "invalid cache" message from Carthage.

I'm not completely sure that this is actually related to SwiftCheck, but I tried to `carthage update --platform iOS  --cache-builds` multiple times in an empty folder with a Cartfile with just SwiftCheck in it, and the cache appears always invalid.

Any ideas?

Thanks

**Comment by CodaFi** [comment]
I think you'll have better luck asking the Carthage folks.  I've never used their caching feature before.

**Comment by ikesyo** [comment]
Submittd #227 to fix this.
