### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by icanswiftabit** [typelift/SwiftCheck#219]
Version
========

0.8.0

Environment
===========

macOS 10.12.5, Xcode 9 9M136h, Carthage 0.23.0

Description
============

I'm trying to build `SwiftChec` with Swift 4 by Carthage. But it fails

Steps To Reproduce
===================

Build SwiftCheck as dependency through Carthage

Expected Result
================

Buildable framework

Actual Result
==============

_What was the actual result after running the steps above?_

Additional information
======================

Error from log

```
/Carthage/Checkouts/SwiftCheck/Sources/Arbitrary.swift:73:27: error: type 'Self' has no member 'multiplyWithOverflow'
                }, initial: self < 0 ? (Self.multiplyWithOverflow(self, -1).0) : self)
                                        ^~~~ ~~~~~~~~~~~~~~~~~~~~
```

**Comment by bkase** [comment]
Hi! We're waiting for TravisCI to support xcode9 before upgrading. @Codafi has a PR up already if you want to play with it on a fork. https://github.com/typelift/SwiftCheck/pull/218

**Comment by akashivskyy** [comment]
Hey, since #218 is now merged, maybe you could release a beta/rc version for Swift 4? 🙃

**Comment by bkase** [comment]
@akashivskyy thanks for the reminder! Here it is: https://github.com/typelift/SwiftCheck/releases/tag/v0.9.0-beta.1
