### ISSUE TITLE
Using SwiftCheck with Sourcery

### ISSUE THREAD

**Issue by cnicolai** [typelift/SwiftCheck#226]
# Using SwiftCheck with Sourcery

Hi,

I hope an "Issue" is the right place to share this. I have been using the awesome [Sourcery](https://github.com/krzysztofzablocki/Sourcery) to make testing with SwiftCheck more easy. Sourcery is a code generation tool for Swift.

## AutoArbitrary

Sourcery can be used to automatically generate conformance to the `Arbitrary` protocol. The following Sourcery template can do so for structs, classes and enums.

```stencil
// MARK: - AutoArbitrary for structs
{% for type in types.implementing.AutoArbitrary %}
{% if type.kind == "struct" or type.kind == "class" %}
// MARK: - {{ type.name }} AutoArbitrary
extension {{ type.name }}: Arbitrary {
    public static var arbitrary: Gen<{{ type.name }}> {
        return Gen<{{ type.name }}>.compose { _ in
            return {{ type.name }}(
                {% for variable in type.storedVariables %}
                {{ variable.name }}: {{ variable.typeName }}.arbitrary{% if variable.annotations %}.suchThat { {{ variable.annotations.itHolds }} }{% endif %}.generate{% if not forloop.last %}, {% endif %}
                {% endfor %}
            )
        }
    }
}
{% endif %}
{% endfor %}

// MARK: - AutoArbitrary for enums

{% for type in types.implementing.AutoArbitrary|enum %}
extension {{ type.name }}: Arbitrary {
    public static var arbitrary: Gen<{{ type.name}}> {
        return Gen<{{ type.name}}>.fromElements(of: [
            {% for case in type.cases %}
            {% if not case.hasAssociatedValue %}
            {{ type.name}}.{{ case.name }}{% if not forloop.last %},{% endif %}
            {% else %}
            {% for assoVal in case.associatedValues %}
            {{ type.name}}.{{ case.name }}({{ assoVal.localName }}{% if not assoVal.localName == nil %}: {% endif %}{{ assoVal.typeName }}.arbitrary){% endfor %}{% if not forloop.last %},{% endif %}
            {% endif %}
            {% endfor %}
        ])
    }
}
{% endfor %}

```

For example, for the following `Point` struct

```swift
struct Point {
    let x: Int
    let y: Int
}
```

the following extension can be created automatically:

```swift
// MARK: - Point AutoArbitrary
extension Point: Arbitrary {
    public static var arbitrary: Gen<Point> {
        return Gen<Point>.compose { _ in
            return Point(
                x: Int.arbitrary.generate, 
                y: Int.arbitrary.generate
            )
        }
    }
}
```

Note that Sourcery can be run frequently, for example as a build phase in Xcode. So if later `let z: Int` is added to `Point`, the extension will be updated automatically.

It is also possible to specify some conditions on the properties, consider the following `Person` struct:

```swift
struct Person {
    // sourcery: itHolds = "$0.characters.count > 0"
    let name: String

    // sourcery: itHolds = "$0 >= 0"
    var age: Int
}
```

The `name` of a `Person` should not be an empty String and the `age` should be non negative. The closures in the comments above the properties are used as follows:

```swift
// MARK: - Person AutoArbitrary
extension Person: Arbitrary {
    public static var arbitrary: Gen<Person> {
        return Gen<Person>.compose { _ in
            return Person(
                name: String.arbitrary.suchThat { $0.characters.count > 0 }.generate, 
                age: Int.arbitrary.suchThat { $0 >= 0 }.generate
            )
        }
    }
}
```

## Protocol conformance

Consider for example the `Comparable` protocol. Types conforming to `Comparable` are required to provide the `<` operator:

```swift
static func < (lhs: Self, rhs: Self) -> Bool
```

And additionally, it is required that the implementation of `<` fulfills

- Irreflexivity
- Antisymmetry
- Transitivity

Writing tests for this by hand is tedious. But with Sourcery, we can automatically create tests for every Type conforming to `Comparable`:

The following template

```stencil
{% for type in types.all|based:"Comparable" %}
class {{ type.name }}ComparableAutoTest: XCTestCase {

    func test{{ type.name }}Comparable() {
        property("Irreflexivity") 
            <- forAll { (a: {{ type.name }}) in
            return !(a<a)
        }

        property("Antisymmetry") 
            <- forAll { (a: {{ type.name }}, b: {{ type.name }}) in
            return (a < b) ? !(b < a) : (b <= a)
        }

        property("Transitivity") 
            <- forAll { (a: {{ type.name }}, b: {{ type.name }}, c: {{ type.name }}) in
            return ( (a<b) && (b<c) ) ==> (a<c)
        }
    }
}

{% endfor %}
``` 

and the following extension to `Person`

```swift
extension Person: Comparable {
    static func < (lhs: Person, rhs: Person) -> Bool {
        return lhs.age < rhs.age
    }
}
```

will deliver the following autogenerated tests:

```swift
class PersonComparableAutoTest: XCTestCase {

    func testPersonComparable() {
        property("Irreflexivity") 
            <- forAll { (a: Person) in
            return !(a<a)
        }

        property("Antisymmetry") 
            <- forAll { (a: Person, b: Person) in
            return (a < b) ? !(b < a) : (b <= a)
        }

        property("Transitivity") 
            <- forAll { (a: Person, b: Person, c: Person) in
            return ( (a<b) && (b<c) ) ==> (a<c)
        }
    }
}
```

-----

All of the above was very helpful for me. I'm curious what you think about this ideas and would be happy to discuss them or come up with new templates and use cases together.

**Comment by bkase** [comment]
@cnicolai This is awesome! Sorry for not responding sooner -- I accidentally cleared my notifications at one point. I think we should include your write-up in a markdown file that we link to from the README or at least point to this issue (feel free to file a PR).

I think we should include Sourcery templates like the one you've made for each algebraic structures' laws inside https://github.com/typelift/Abstract . There are a few pieces of administrivia that need to be taken care of on that repo, but then I really will try hard to get people using it!

Your Sourcery templates would be a great addition there, please send a PR!

**Comment by broomburgo** [comment]
We've been experimenting with Sourcery at work for a while, and we're currently using it in production for autogeneration of Equatable conformance, along with lenses and prisms definitions for structs and enums. I think that, after having agreed upon a suitable set of templates to be digested by Sourcery for Arbitrary (also CoArbitrary would be interesting), we could actually ship them with the SwiftCheck project itself, along with instructions to use them.

I like @bkase idea to add Sourcery templates for the laws in Abstract: I'm going to assign myself an issue to do that :D

**Comment by cnicolai** [comment]
Hi @bkase, hi @broomburgo

Thank you for your answers and your interest!

I think the following points would be interesting:

1. Auto conformance to Arbitrary / CoArbitrary (I would like to understand what that is anyways)

2. Generating tests to check whether a type "really" conforms to a protocol. "Really" meaning that not only the signature of the function has to be correct, but that also certain properties have to hold. The compiler is satisfied easily:

```swift
struct Point {
    let x: Int
    let y: Int
}

extension Point: Equatable {
	static func == (lhs: Point, rhs: Point) -> Bool {
		let decision = Int.arbitrary.generate
		if decision >= 0 {
			return true
		} else {
			return false
		}
	}
}
```

I'm not too familiar with all the protocols in the standard library, but I guess it would be cool to provide templates for those and to write an explanation how people could write templates for their own protocols.

I will also have a look at Abstract. As a mathematician, it makes me feel right at home :)

I will be very busy in the next two weeks and most likely won't have any time, but I will happily send a PR afterwards.

**Comment by cnicolai** [comment]
Hi,
I just wanted to let you know that I didn't forget you or the promised PR, I'm just too busy right now due to some unplanned projects and it will be a couple of weeks until I'll get to it.
Cheers!

**Comment by cnicolai** [comment]
Hi guys, hi @bkase 
sorry for letting you wait for so long. Unfortunately, I didn't have any time for iOS/Swift Development in the past months, and the upcoming months until June/July don't seem to get any better.

At the moment, all I can offer are the templates, explanations and suggestions in the comments above. I really hope (and plan!) to start writing Swift again this summer, and if I will be able to do so (likely, but not guaranteed) , I will definitely use SwiftCheck then.

So, if that is okay for you, leave this issue open and we will see what summer brings.
However, if this open issue is just noise you want to avoid, feel free to close it.

**Comment by Zeta611** [comment]
This looks great!
