### ISSUE TITLE
[Swift 4.0] Argument labels '(extendingOrTruncating:)' do not match any available overloads

### ISSUE THREAD

**Issue by acrookston** [typelift/SwiftCheck#235]
Version
========

`origin/swift-develop` at `f2e5b35`

Environment
===========

Xcode 9 Beta 5
Running on macOS Sierra 10.12.5 (16F73)

Description
============

Experimenting with Xcode 9 beta 5, while bootstrapping with Carthage this library failed to build. I cloned the source and tried building manually and it also fails. I see several errors like this:
`Argument labels '(extendingOrTruncating:)' do not match any available overloads`
Removing the `extendingOrTruncating` label does allow the build to run but I do not know if these are required for the library to work correctly.

Happy to submit a PR if just removing the label is the correct fix.

Steps To Reproduce
===================

- Install Xcode 9 beta 5 (I recommend using `xcversion` via `gem install xcversion`).
- Clone source
- Checkout `origin/swift-develop`
- Build in Xcode

Expected Result
================

Build to pass

Actual Result
==============

Build failing with error `Argument labels '(extendingOrTruncating:)' do not match any available overloads`.

**Comment by DylanLukes** [comment]
The method `init(extendingOrTruncating:)` has been renamed `init(truncatingIfNeeded:`) as per proposal [SE-104](https://github.com/apple/swift-evolution/blob/master/proposals/0104-improved-integers.md).

**Comment by CodaFi** [comment]
Resolved by the merge of #235.
