### ISSUE TITLE
Release version 0.9.1 (as 0.9.2) to CocoaPods

### ISSUE THREAD

**Issue by akashivskyy** [typelift/SwiftCheck#258]
### Description

Right now the latest SwiftCheck version is 0.9.1, but [the latest version that CocoaPods sees](https://github.com/CocoaPods/Specs/tree/master/Specs/1/a/1/SwiftCheck) is 0.8.1.

As CocoaPods requires `.podspec` files to be tagged _before_ pushing a git tag, it's not possible to publish existing 0.9.1 to CocoaPods trunk. Instead, it's required to bump the patch version to 0.9.2 in `.podspec`, push the tag and then release it to CocoaPods.

### Steps To Reproduce

```
$ pod repo update
$ pod search SwiftCheck
```

### Expected Result

SwiftCheck 0.9.1 is the latest version seen by CocoaPods.

### Actual Result

Actually it's 0.8.1.

**Comment by CodaFi** [comment]
I've been having a load of trouble with Cocoapods since they seem to have abandoned the idea that macOS 10.12.x is a thing that people still use.  Just reinstalled everything and pushed 0.9.0 to their trunk (with warnings on Xcode 9.1).  Will do 0.9.1 a little later.

**Comment by CodaFi** [comment]
0.9.1 just went out - turns out you can bump after you tag.

Thanks for giving me the kick in the pants to get this done.

**Comment by akashivskyy** [comment]
>turns out you can bump after you tag.

TIL, all tutorial were suggesting otherwise and I've been following that rule. 🤦‍♂️
