### ISSUE TITLE
Feature Request: Non-custom-operator-based methods equivalents

### ISSUE THREAD

**Issue by alexhuang91** [typelift/SwiftCheck#261]
It would be great to be able to call a method instead of using the custom '<-' operator. This would enable adoption in codebases that strongly discourages the use of custom operators.

```
/// Binds a Testable value to a property.
public func <- (checker : AssertiveQuickCheck, test : @autoclosure @escaping () -> Testable) {
	handleQuickCheckWithResult(checker: checker, test: test)
}

public func handleQuickCheckWithResult(checker : AssertiveQuickCheck, test : @autoclosure @escaping () -> Testable) {
	switch quickCheckWithResult(checker.args, test()) {
	case let .failure(_, _, seed, sz, reason, _, _):
		XCTFail(reason + "; Replay with \(seed) and size \(sz)", file: checker.file, line: checker.line)
	case let .noExpectedFailure(_, seed, sz, _, _):
		XCTFail("Expected property to fail but it didn't.  Replay with \(seed) and size \(sz)", file: checker.file, line: checker.line)
	case let .insufficientCoverage(_, seed, sz, _, _):
		XCTFail("Property coverage insufficient.  Replay with \(seed) and size \(sz)", file: checker.file, line: checker.line)
	default: ()
	}
}
```

[Check.swift:162](https://github.com/typelift/SwiftCheck/blob/master/Sources/SwiftCheck/Check.swift#L162)

Since the switch statement is on quickCheckWithResult(...), handleQuickCheckWithResult(...) seems like an appropriate name.

**Comment by CodaFi** [comment]
It's not publicized very well but if you just want to execute a test "quickly", we provide `quickCheck(_:name:)` [here](https://github.com/typelift/SwiftCheck/blob/master/Sources/SwiftCheck/Test.swift#L540).  

Did you have something else in mind?

**Comment by alexhuang91** [comment]
If I understand correctly, that would drop the handling of the result. The code snippet above was what I had in mind.

**Comment by CodaFi** [comment]
Let me cook something up.  I’m traveling today, but should be able to push things in between.
