### ISSUE TITLE
Add tag `property-based-testing`

### ISSUE THREAD

**Issue by felix91gr** [typelift/SwiftCheck#269]
I was browsing [this](https://github.com/topics/property-based-testing) on GH and I thought it was strange that SwiftCheck wasn't appearing.

But of course it was. It didn't have this tag. I think it could use it, what do you think? :)

_PS: sorry for the unfinished posting, it was a misstap. Now it's complete_

**Comment by harlanhaskins** [comment]
Done. Thanks for the suggestion!
