### ISSUE TITLE
no Gen.let or heterogeneous sequence/tuple?

### ISSUE THREAD

**Issue by johanatan** [typelift/SwiftCheck#276]
i.e., 
https://github.com/clojure/test.check/blob/master/src/main/clojure/clojure/test/check/generators.cljc#L1585-L1588

and
https://github.com/clojure/test.check/blob/master/src/main/clojure/clojure/test/check/generators.cljc#L82-L87

Any workarounds approaching these other than nesting `flatMap`s (which would become rather unwieldy)?

**Comment by johanatan** [comment]
Ah, I found `Gen<DEST_TYPE>.map(G0, G1, ... GN)`. That should suffice for this.

**Comment by johanatan** [comment]
Also, `Gen.compose`.

**Comment by CodaFi** [comment]
`Gen.compose` is definitely your friend here for tuples of large arity.

**Comment by johanatan** [comment]
Does that mean I have to define classes to hold them or is there a way to actually produce a Tuple directly from Gen.compose?
