### ISSUE TITLE
`forAll` doesn't support explicit generator being passed

### ISSUE THREAD

**Issue by johanatan** [typelift/SwiftCheck#277]
i.e.,  the version of forAll as depicted below and referring to in docs and tutorials doesn't seem to be included in the actual latest pod release:

`forAll(someGenerator) { // the checker }`

I was able to get:
`forAllNoShrink(someGenerator) { // the checker }`
to compile however.

When `someGenerator` is a fairly simple conglomeration of primitive generators, I'd image a shrinking strategy to be available and thus the former to actually compile/work. Is there something I'm missing?

**Comment by CodaFi** [comment]
In order for `forall` to shrink your type with your explicit generator, its underlying value type must conform to `Arbitrary`.  If, for example, you have a generator of tuples, you currently cannot convince Swift that your generator conforms to `Arbitrary` as it doesn't cannot expression protocol conformances for non-nominal types.

For that, and for more complex collections, you can use a [Modifier Type](https://github.com/typelift/SwiftCheck/blob/master/Sources/SwiftCheck/Modifiers.swift#L11).

**Comment by johanatan** [comment]
One of the cases where this failed for me is a generator of a custom class (which is just being used as a dumb struct because obj-c can't consume actual Swift structs) that I have in my project. 

Here's the definition of it if that helps you diagnose:

```
    static func detectObjGenGen(strGen: Gen<String>) -> Gen<YUMMLDetectObject> {
        let pointExtentGen =
            Gen<Double>.choose((0, 1)).flatMap {
                sequence([Gen.pure($0), Gen<Double>.choose((Double.ulpOfOne, 1.0 - $0))]).map {
                    ($0.first!, $0.last!)
                }
            }

        let rectGen = sequence([pointExtentGen, pointExtentGen]).map { ($0.first!, $0.last!) }
        return Gen<YUMMLDetectObject>.zipWith(strGen, Gen<Double>.choose((0, 1)), rectGen,
                                   transform: { (lbl, score, rect) -> YUMMLDetectObject in
            let pt1 = rect.0
            let pt2 = rect.1

            assert(pt1.0 + pt1.1 <= 1.0)
            assert(pt2.0 + pt2.1 <= 1.0)
            assert(pt1.1 >= 0.0 && pt1.0 >= 0.0)
            assert(pt2.1 >= 0.0 && pt2.0 >= 0.0)

            let rect = CGRect.init(x: pt1.0, y: pt2.0, width: pt1.1, height: pt2.1)
            let detCat = NearestDetections.scoreToDetectionCat(score: Float(score))
            return YUMMLDetectObject.init(box: rect, label: lbl as NSString, score: Float(score),
                                          imageDims: CGSize.zero,
                                          detectionCategory:detCat)
        })
    }

    static let detectObjGen = detectObjGenGen(strGen: String.arbitrary)
```
Not sure what the "underlying value type" here would be but this is built from a combination of primitive generators as you can see.

**Comment by CodaFi** [comment]
Does `YUMMLDetectObject` conform to `Arbitrary`?

**Comment by johanatan** [comment]
Doubtful. How can I make that so?

**Comment by CodaFi** [comment]
If you control the declaration of `YUMMLDetectObject`, you can pretty safely add a conformance with an `extension`.  If you don't control the declaration, you can add an orphan instance in your module or declare a wrapper type.

**Comment by johanatan** [comment]
Perfect. Thank you!

**Comment by johanatan** [comment]
So, this is now working for me with an explicit `Arbitrary` conformance specified. But it seems a bit odd that my Arbitrary definition refers to the _exact_ generator originally passed to `forAll`. Why can't `forAll` just take that generator it was provided and assume that it will be the definition of any `Arbitrary` that would be defined for it?

**Comment by CodaFi** [comment]
> Why can't forAll just take that generator it was provided and assume that it will be the definition of any Arbitrary that would be defined for it?

So, we could do this, and if you think about it backwards, this is kind of how the whole shebang works.  `Arbitrary` is shorthand for "this type has a generator and a shrinker" and forAll simply shells out to `forAllShrink` with those values as arguments.  So if you intend to use the shorthand, you have to play ball with a protocol conformance.  If you intend to be explicit, you have to be explicit everywhere.

**Comment by johanatan** [comment]
Ah, so then I could just call `forAllShrink` directly without having to define an `Arbitrary`?
