### ISSUE TITLE
Doesn't compile with Xcode 10.2

### ISSUE THREAD

**Issue by raysarebest** [typelift/SwiftCheck#287]
Version
========

SwiftCheck v0.11.0 `228bc5e44f09dcea617013f9c022efdbcc61c9d9`

Environment
===========

macOS 10.14.4, Xcode 10.2, CocoaPods 1.7.0.beta.2, Carthage 0.32.0

Description
============

The latest release version does not compile with Xcode 10.2 because its Swift version is still Swift 3

Steps To Reproduce
===================

Either checkout this module at the latest release commit or use it as a dependency via Carthage or CocoaPods in another project and attempt to compile this module with Xcode 10.2

Expected Result
================

The module compiles and functions properly

Actual Result
==============

The module fails to compile

Additional information
======================

It looks like the `master` branch has already been updated with the code-level support needed to make this module work with Xcode 10.2. However, the current commit in `master` needs to be tagged as a release and then pushed to CocoaPods

**Comment by sebastiangrail** [comment]
[The latest release](https://github.com/typelift/SwiftCheck/releases/tag/0.12.0) now targets Swift 5 and Xcode 10.2
