### ISSUE TITLE
Propagate File and Line Number with Test

### ISSUE THREAD

**Issue by CodaFi** [typelift/SwiftCheck#33]
XCTAssert is landing inside of us instead of inside of the test.

**Comment by CodaFi** [comment]
Way I see it there's only one course of action: property has to take implicit parameters, which means it can no longer be a subscript.

**Comment by pthariensflame** [comment]
Why not have `forAll` take implicit parameters instead?

**Comment by CodaFi** [comment]
Because not all properties use it.

**Comment by pthariensflame** [comment]
Oh, well; we can always use an operator like `<~` or something instead of `=`, and then just replace the indexing syntax with a normal function call.

**Comment by CodaFi** [comment]
@pthariensflame That sounds like a plan.  I can draw up a pull request for that.
