### ISSUE TITLE
An Applicator For Property Combinators

### ISSUE THREAD

**Issue by CodaFi** [typelift/SwiftCheck#34]
Having to write

```swift
property["foo"] = verbose(forAll { //
})
```

Is kind of ridiculous when we could instead be doing this

```swift
property["foo"] = forAll { //
} $ verbosely
```

Or this

```swift
property["foo"] = verbose $ forAll { //
}
```

Flipping the Combinators isn't hard, it's the operator we'd have to define that troubles me.  There are too many interpretations of apply among the Swift community (I should know, I've written at least 2 of them).  I don't want to tread on toes, nor do I want to define yet another random operator and deepen the DSL.

Halp?

**Comment by robrix** [comment]
I nominate Prelude’s interpretation of `|>` :stuck_out_tongue:

**Comment by robrix** [comment]
Actually tho, that seems like something that could be left to Prelude (or another library) if the user happens to be using one.

**Comment by CodaFi** [comment]
My thing is if we happen to export our own declaration of `|>` then Swift will start throwing up ambiguous operator declarations in every piece of code that touches both SwiftCheck and that library.

**Comment by robrix** [comment]
That’s why I’m suggesting we leave this one for consumers. SwiftCheck doesn’t need to solve this problem.

**Comment by CodaFi** [comment]
Oh, but I wish it could...

**Comment by robrix** [comment]
Pick your battles :smile:

**Comment by CodaFi** [comment]
Fine.  Ugly syntax it is.

:pouting_cat:
