### ISSUE TITLE
Test that properties fail correctly

### ISSUE THREAD

**Issue by robrix** [typelift/SwiftCheck#47]
The test for `exists` in #45 is simply returning `true`. A more interesting property of `exists` is its failure when something _doesn’t_ exist.

My tests in [Assertions](https://github.com/antitypical/Assertions) do [a little trickery](https://github.com/antitypical/Assertions/blob/master/AssertionsTests/AssertionsTests.swift#L81-L113) ([discovered by](https://github.com/antitypical/Assertions/pull/3#issuecomment-76337761) @ishkawa) to enable testing assertion failures without actually failing its own tests. It would be nice to use something like this to test that properties which don’t hold, fail.

**Comment by CodaFi** [comment]
Thing is: our ∃ cannot discern the difference between failure and the RNG skipping or not even reaching a value.  Until I have a finer-grained understanding of what it means to fail in an existential built into that pull request I wouldn't know what to test.

**Comment by robrix** [comment]
Ok, not a great example. Being able to test property failure correctly in the general case is still useful.

**Comment by CodaFi** [comment]
Mhm... I'm thinking the existential is only good as a synonym for `¬ ∀ {x} . P x` [basically, proving a test case should never hold given elements of x's domain] at this point.  If you manage to make anything concrete you know what to do!

**Comment by CodaFi** [comment]
OK, now that I read this over again Past Me decided talking last you was a productive avenue.  He is an idiot.

So what about this is different from the `expectFailure` combinator?  That XCTFail is invoked is an implementation detail of the particular checking strategy the user has chosen for a property, so it may not always be possible to use your kit.  Probably could do something like what you have with `mapProp` et al.

**Comment by robrix** [comment]
Ah, I understand the miscommunication now.

I’m not talking about using SwiftCheck to test the failure of _my_ code’s properties. Instead, I would like for SwiftCheck to verify (via its tests) that if some arbitrary property doesn’t hold, the test fails. And specifically that this should be the case for `exists`, because [the PR only tests that it succeeds when `true`](https://github.com/typelift/SwiftCheck/pull/45/files#diff-a39c9ec9dfce48179914ed3cc5d77cf8R35), not that it fails when `false`, and the latter property cannot be inferred from the former..
