### ISSUE TITLE
SwiftCheck fails to build as Carthage dependency

### ISSUE THREAD

**Issue by griotspeak** [typelift/SwiftCheck#68]
I checked out SwiftCheck/swift-develop and it builds without issue as a standalone Xcode project. When I include Swiftx, which includes SwiftCheck, the build fails (`A shell task failed with exit code 65`) but I am unsure of the cause. The only error that I can find in the log is 

    ~/Development/TonalKit/Carthage/Checkouts/Swiftx/Carthage/Checkouts/SwiftCheck/SwiftCheck/Test.swift:489:28: error: cannot invoke 'flatMap' with an argument list of type '((_) -> _)'
	        let strings = s.collected.flatMap({ l in Array(l).map({ "," + $0.0 }).filter({ !$0.isEmpty }) })
	                                  ^
	~/Development/TonalKit/Carthage/Checkouts/Swiftx/Carthage/Checkouts/SwiftCheck/SwiftCheck/Test.swift:489:28: note: overloads for 'flatMap' exist with these partially matching parameter lists: (@noescape (Self.Generator.Element) -> S), (@noescape (Self.Generator.Element) -> T?)
	        let strings = s.collected.flatMap({ l in Array(l).map({ "," + $0.0 }).filter({ !$0.isEmpty }) })

Though it seems to keep building past that and then stop on Rose.swift without explicitly providing an error.

**Comment by CodaFi** [comment]
Beta 4 overloaded flatMap and broke that.  Hold for a fix.

**Comment by CodaFi** [comment]
Come to think of it... That looks like old code.  The newer version breaks that up into multiple lines and should work just fine.  ⌘+⇧+⌥+K?

**Comment by CodaFi** [comment]
`carthage update`

**Comment by griotspeak** [comment]
:+1:
