### ISSUE TITLE
Report on which sub-property failed

### ISSUE THREAD

**Issue by brentleyjones** [typelift/SwiftCheck#74]
I may be doing something wrong, but when I use sub properties and one of them fails, all I get in the output are the inputs used and the name of the parent property. For example:

```swift
property("equtatable") <- forAll {
    (a: Int, b: Int) in
            
    let reflexive = EquatableTestUtilities.checkReflexive { Constant(a) } <?> "reflexive"
    let symmetric = EquatableTestUtilities.checkSymmetric { Constant(a) } <?> "symmetric"
    let transitive = EquatableTestUtilities.checkTransitive { Constant(a) } <?> "transitive"
    let notEquate = (a != b) ==> {
        EquatableTestUtilities.checkNotEquate(
            { Constant(b) },
            { Constant(b) }
        )
    }() <?> "not-equate"
            
    return reflexive ^&&^ symmetric ^&&^ transitive ^&&^ notEquate
}
```

will just say that "equatable" failed, instead of also telling me that "not-equate" failed:

```
*** Failed! Proposition: equtatable
Falsifiable (after 1 test):
0
1
*** Passed 0 tests
```

If I get it to go past 1 test, it looks even weirder, saying 100% of the sub-properties passed?:

```
*** Failed! Proposition: equtatable
Falsifiable (after 2 tests and 2 shrinks):
-2
0
*** Passed 1 tests
(100%, not-equate, transitive, symmetric, reflexive)
```

---

Basically, I feel it would be really valuable to know which sub-properties have failed. Sometimes custom arbitrary types are expensive to compute and it's easier to do many sub-properties off the same random values.

**Comment by CodaFi** [comment]
You may want to use disjunction (`^||^`) instead.  `^&&^` is for precisely the case you're trying to avoid here: treating multiple sub-properties as one contiguous entity.

**Comment by CodaFi** [comment]
I do see a bug in the pluralizer, tho.  That will be fixed shortly.

**Comment by CodaFi** [comment]
As for the matter of expensive objects in tests, it may be possible SwiftCheck is causing over-retains if you happen to capture things inside the testing block (which gets bandied around quite a bit of tree-mutations before actually being invoked).  The natural solution to this is to use a smart-pointer-esque value type.

Otherwise the only other thing I can think of 2 other ways to help with this:

1) (if expensive means the type is recursive) using [Actions](https://github.com/typelift/Concurrent/blob/swift-develop/ConcurrentTests/MVarSpec.swift#L13) rather than direct instances of `Arbitrary` has been very helpful.

2) (if expensive means expensive) You may consider using [once](https://github.com/typelift/SwiftCheck/blob/swift-develop/SwiftCheck/Property.swift#L99) with some outer test block that returns the actual test inside the block.  Like

```
forAll { (x : ExpensiveFoo) in
   return forAll { (a : Int, b : Int)
        return x.doTestedThings(a, b)
   }
}.once
```

**Comment by brentleyjones** [comment]
Thank you for taking the time to respond to this.

I see in the comments now about how conjunction will mask lower failures. Going directly to disjunction though isn't very useful, since I want a failure if any of them fail the whole. Based on your comment it seems that to get that I  have to make a convoluted combination of them (which I currently can't picture, sorry about that).

Also, I'm only testing values right now, so it's not over-retains. It's simply lots of Dictionaries :smile:. `once` is a good tip, but in this case I want to have a normal spread of randomness on the values, I just want to be able to do many different tests with those values, and if a single one of those tests fail I want to whole to fail.

**Comment by CodaFi** [comment]
Try `verbose` along with your sub-properties then for initially failing tests.  SwiftCheck should give you a TMI view of things that will allow you to patch your test cases one by one until you can peel off the band-aid and go back to regular old conjunctions.

**Comment by brentleyjones** [comment]
Okay. That's a good bandaid, but given randomness, it might take a bit for it to happen again. In that case, I would instead take the inputs given and manually try each of the sub-properties until I saw which one was failing... which seems to fly in the face of the FIRST principle for tests, and really isn't something I would expect contributors to my project to try to figure out if they get a failing test case.

Anyway, it does seem that I wasn't really doing anything wrong, this just isn't supported currently, in the way I want to use it. I would understand if no change will be made for it, it just seemed counter-intuitive that it didn't report which sub-property was failing (I feel in the conjunction case, regardless of what it is, if you gave it a label that means it's important enough to be reported on in the failure case).

**Comment by CodaFi** [comment]
That seems a bit hyperbolic.  Manual, here, looks like this

    return reflexive.verbose ^&&^ symmetric.verbose ^&&^ transitive.verbose ^&&^ notEquate.verbose

Then you just take off the verboses for passing cases.  Point is QuickCheck (and by extension, SwiftCheck) care about the test case as a piece of data.  You have all the tools you need to examine the sub-parts of a failing test already, it's just a matter of using the right combination to produce a passing test.

**Comment by brentleyjones** [comment]
I personally think that when a test fails I should be able to tell why it failed, without having to modify it. I can agree to disagree here though.

So, I did exactly what you prescribed, and I think I ran into a different issue:

```
Failed:
*** Failed! Failed:
Proposition: equtatable
Falsifiable (after 1 test and 2 shrinks):
0
1
*** Passed 0 tests
```

It doesn't seem to be outputting the label of the sub-property.

**Comment by CodaFi** [comment]
> I personally think that when a test fails I should be able to tell why it failed, without having to modify it

SwiftCheck is rather bare-bones about it because you have access to quite a bit of the testing mechanism to produce custom output.  Or perhaps the original authors were lazy, who knows?  :stuck_out_tongue: 

If you can find a way to make this work while still maintaining modularity, I'll merge it.

> It doesn't seem to be outputting the label of the sub-property.

There is no sub-property here.  `verbose` applies to the entity it is attached to, not the whole test (you can try .verbose on the whole shebang to see that).

**Comment by brentleyjones** [comment]
>  There is no sub-property here. `verbose` applies to the entity it is attached to, not the whole test (you can try .verbose on the whole shebang to see that).

Does that mean:

```
Passed:
Passed:
Passed:
Passed:
Failed:
```

isn't bugged? Each entity had a label (via `<?>`) and `.verbose`.

---

For the time being `whenFail` with `print` works really well, thank you for that tip. I'll see where that leads me and maybe I can come up with something that is merge worthy if this continues to bug me :wink:.

**Comment by CodaFi** [comment]
Hmph, that may be something that can be fixed.  That's expected output from QuickCheck, but you're right: we have a chance to do it better here.  I'll see what I can do.

**Comment by CodaFi** [comment]
With the merge of #76 I will close this.  If you have anything further to add, or I managed to not fix anything, feel free to reopen it or another issue.
