### ISSUE TITLE
Cocoapod?

### ISSUE THREAD

**Issue by zbeckman** [typelift/SwiftCheck#78]
Please? ;-)

Seriously, this would be a great pod.

**Comment by CodaFi** [comment]
Would you be willing to contribute one?  I don't use pods myself and have done it very wrong in the past.

**Comment by zbeckman** [comment]
I might be able to do that... Let me look into it. We have a need of integrating a good check library into our project, and a strong preference for Cocoapods where possible...

**Comment by CodaFi** [comment]
I'd appreciate anything you could do.

**Comment by zbeckman** [comment]
Started looking into this – but I'm having trouble with a few things. Would be nice to have the docs improved to include information on how to build and install into other projects, etc.

Right now – seem to be a bit stuck on how to generate a framework for inclusion in an iOS Project.

Also running into some build problems during podding... will come back to those. If you can give a little advice on your build setup / install instructions that could prove helpful.

**Comment by CodaFi** [comment]
You're right in that the README should definitely have installation instructions.  As for the failing pod builds, can you be more specific?

**Comment by zbeckman** [comment]
Yep... here's the error I'm trying to figure out. The build works fine in Xcode, but during podding I get this...

/Users/zbeckman/Projects/SwiftCheck/SwiftCheck/TestOperators.swift:120:13: error: cannot load underlying module for 'XCTest'
import func XCTest.XCTFail
            ^

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /Users/zbeckman/Projects/SwiftCheck/SwiftCheck/Arbitrary.swift
	CompileSwift normal x86_64 /Users/zbeckman/Projects/SwiftCheck/SwiftCheck/Check.swift
	CompileSwift normal x86_64 /Users/zbeckman/Projects/SwiftCheck/SwiftCheck/Equatable.swift
	CompileSwift normal x86_64 /Users/zbeckman/Projects/SwiftCheck/SwiftCheck/Gen.swift
	CompileSwift normal x86_64 /Users/zbeckman/Projects/SwiftCheck/SwiftCheck/Lattice.swift
	CompileSwift normal x86_64 /Users/zbeckman/Projects/SwiftCheck/SwiftCheck/Modifiers.swift
	CompileSwift normal x86_64 /Users/zbeckman/Projects/SwiftCheck/SwiftCheck/Property.swift
	CompileSwift normal x86_64 /Users/zbeckman/Projects/SwiftCheck/SwiftCheck/Random.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(9 failures)
 -> SwiftCheck (1.0.0b)
    - ERROR | [iOS] Returned an unsuccessful exit code.
    - ERROR |  /Users/zbeckman/Projects/SwiftCheck/SwiftCheck/TestOperators.swift:120:13: error: cannot load underlying module for 'XCTest'

**Comment by CodaFi** [comment]
Ah!  Take a look at how other frameworks that need to link XCTest get around that.  We use header search paths to trick Xcode; I'm not sure how to do that with Pods tho.

**Comment by CodaFi** [comment]
Here's [Quick](https://github.com/Quick/Quick/blob/swift-2.0/Quick.podspec)

**Comment by zbeckman** [comment]
Aha! Thanks that helps...

**Comment by zbeckman** [comment]
Alright, this is a bit frustrating – not sure if you are more familiar with the command line compiler than I am. I don't use it...

Running into a problem where overloaded operators (such as <^>) are throwing errors during compile:

/Users/zbeckman/Projects/SwiftCheck/SwiftCheck/Gen.swift:205:13: error: operator implementation without matching operator declaration
public func <^> <A, B>(f : A -> B, g : Gen<A>) -> Gen<B> {
/Users/zbeckman/Projects/SwiftCheck/SwiftCheck/Rose.swift:30:12: error: operator is not a known binary operator
                return f <^> self

Now, obviously these are declared in Operators.swift. My first thought was to try and import the SwiftCheck package – but that doesn't work ("can't import package being compiled"). If you have any ideas please do holler... will research more, but I have to get back to a few other things for this afternoon...

**Comment by CodaFi** [comment]
They come from another TypeLift package called Operadics.

**Comment by CodaFi** [comment]
You're gonna want to enable submodules and let the pod see External/Operadics

**Comment by CodaFi** [comment]
With the merging of #83 SwiftCheck is now registered with Cocoapods and includes a podspec on the 1.2 side.  

I believe that is the end of this issue, then.  Closing.

**Comment by zbeckman** [comment]
Awesome! Looking forward to seeing it pop into the swift 2 branch.

**Comment by zbeckman** [comment]
Hm... Just tried (on my own fork) adding the podspec to swift-develop – The pod downloads and integrates just fine, but during compile I get a lot of compiler errors re: "not a legal operator." Looks like Operadics is not getting pulled into the project. So, it would seem that if you are using a purely Cocoapod setup a piece is still missing...?

**Comment by CodaFi** [comment]
Operadics was added post-1.2 as we split Swiftz into a bunch of other frameworks.  If you want it you have to add the Operadics directory to the source locations pods will search.
