### ISSUE TITLE
Real world examples badly needed in documentation

### ISSUE THREAD

**Issue by zbeckman** [typelift/SwiftCheck#84]
It would be incredibly helpful to see a few "real world" examples in the documentation. Things that we are trying to piece together...
1. Generating 100 random email addresses (with Unicode!)
2. Generating 100 randomized IPv6 address
3. Generating 100 random first, middle, last name combinations
4. Generating 100 random phone numbers (with country code and variable format: ##-####-### etc.)
5. Generating a random phrase of pseudo-latin N words long
6. Generate a binary data stream N bytes long

**Comment by zbeckman** [comment]
Here's a few more:
1. Random passwords that are N characters long with at least 1 symbol, 1 letter, 1 number
2. Random passwords that intentionally violate the above rules

**Comment by CodaFi** [comment]
I chose to leave out things like this because they are often implementation dependent.  But if you wish, I can include either a wiki aggregating common generators or provide an addendum in `Gen.swift` with some of these.

**Comment by CodaFi** [comment]
Here are some common ones I've come up with

```swift
let upper = Gen<Character>.fromElementsOf("A"..."Z" as ClosedInterval<Character>)
let lower = Gen<Character>.fromElementsOf("a"..."z" as ClosedInterval<Character>)
let numeric = Gen<Character>.fromElementsOf("0"..."9" as ClosedInterval<Character>)
let special = Gen<Character>.fromElementsOf(["!", "#", "$", "%", "&", "'", "*", "+", "-", "/", "=", "?", "^", "_", "`", "{", "|", "}", "~", "."])
```

Email:

```swift
private func wrap3(l : String) -> String -> String -> String -> String -> String {
	return { m in { m2 in { m3 in { r in l + m + m2 + m3 + r } } } }
}

let localEmail = Gen<Character>.oneOf([
	upper,
	lower,
	numeric,
	special,
]).proliferateNonEmpty().suchThat({ $0[$0.endIndex.predecessor()] != "." }).fmap(String.init)
let hostname = Gen<Character>.oneOf([
	lower,
	numeric,
	Gen.pure("-"),
]).proliferate().fmap(String.init)
let tld = Gen<Character>.oneOf([
	lower,
]).proliferateNonEmpty().suchThat({ $0.count > 1 }).fmap(String.init)

let emailGen = wrap3 <^> localEmail <*> Gen.pure("@") <*> hostname <*> Gen.pure(".") <*> tld
```

**Comment by zbeckman** [comment]
These are great examples. I'd urge adding them to the documentation – yes, they are implementation specific, but it's more about showing how to use SwiftCheck. Sure, we'll all change the implementation, but figuring out the basic starting place... it's tricky. A few examples go a long way!

**Comment by CodaFi** [comment]
With the merging of #86 this issue is now closed.

Thank you for the help.  I'll continue to push some of the examples listed here as I draw them up.
