### ISSUE TITLE
Examples (from docs) fail to compile in Swift 2 (Xcode 7 beta 6)

### ISSUE THREAD

**Issue by zbeckman** [typelift/SwiftCheck#85]
A few examples from the documentation do not compile in Xcode 7 beta 6:
```
let vowels = Gen.elements(["A", "E", "I", "O", "U" ])
```
Generates the error: Argument for generic parameter "A" could not be inferred.

Also:
```
let weightedOptionals = Gen.frequency([
	(1, Gen.pure(OptionalOf(Optional<A>.None))),
	(3, liftM({ OptionalOf(Optional<A>.Some($0)) })(m1: Int.arbitrary))
])
```
Gives: Use of undeclared type 'A'.

The latter can be fixed up by changing A to Int (for example).

**Comment by CodaFi** [comment]
I'm not sure how these ever worked to be honest.  1.2 was a weird release...

**Comment by CodaFi** [comment]
With the merging of #86 this issue is now closed.
