### ISSUE TITLE
ClosedInterval<Character> does not compile in Swift 2 (Xcode 7 beta 6)

### ISSUE THREAD

**Issue by zbeckman** [typelift/SwiftCheck#87]
It appears that:
```
let upper = Gen<Character>.fromElementsOf("A"..."Z" as ClosedInterval<Character>)
```
Fails to compile in Swift2 (Xcode 7 beta 6) with the following error:
```
Cannot convert value of type 'ClosedInterval<Character>' to expected argument type '[Character]'
```

**Comment by CodaFi** [comment]
I've changed the overloading of `fromElementsOf` for intervals.  It is now called `fromElementsIn`.

**Comment by zbeckman** [comment]
So you did... sorry bout that. Very strange, my first carthage update didn't take... but after project clean and 'delete derived data' all is good. :)
