### ISSUE TITLE
Gen.chooseNum() aka proliferateSized(min, max)

### ISSUE THREAD

**Issue by zbeckman** [typelift/SwiftCheck#88]
It would be great to have an ability to build generators that generate a specific (but random) range. For example, taking from my Scala code:
```
def unicodeGenerator(generator: Gen[Char] = Gen.alphaChar, minimum: Int = 5, maximum: Int = 20): Gen[String] = Gen.chooseNum(minimum, maximum).flatMap { n =>
	Gen.buildableOfN[String, Char](n, generator)
}
```
The above generates a random series of Unicode between 5 and 20 characters. Another expression that's pretty useful:
```
val shortCodeGenerator: Gen[String] = Gen.chooseNum(3, 10).flatMap { n =>
	Gen.sequence[String, Char](List.fill(n)(Gen.alphaNumChar))
}
```
In this latter example, I'm creating an alphanumeric code that is 3 to 10 characters in length.

It would be very handy to be able to specify a range as in proliferateSized(min, max).

**Comment by CodaFi** [comment]
If you know the range then fromElementsIn can be used as a size block.

**Comment by zbeckman** [comment]
Not sure I understand how to do that... in this specific case. For example: How would you write a generator that returns a string consisting of between 10 and 20 characters, randomly variable?

**Comment by CodaFi** [comment]
```swift
let gg : Gen<String> = Gen<Int>.fromElementsIn(10...20) >>- { size in
	return Gen<Character>.fromElementsIn("A"..."Z").proliferateSized(size).fmap(String.init)
}
```

**Comment by zbeckman** [comment]
Perfect! I think that meets the need. Maybe add to an example or the docs? (Figuring out how to use SwiftCheck is tricky without complete docs – even when I do dig into the code and try to reverse engineer features).

**Comment by zbeckman** [comment]
It would be great if the docs added some explanation of `<^>`, `<*>`, `>>-` and other functional artifacts that are not familiar to Swift programmers (or Scala programmers for that matter). I get the general idea that these apply a function across a set of parameters but I have yet to read the code, and figure out exactly how they differ and what they mean.

**Comment by CodaFi** [comment]
The operators are undocumented because they would be duplicates of the combinators they map to above each one, but I take your meaning.

**Comment by CodaFi** [comment]
LOL, I actually gave that as the example for bind!

https://github.com/typelift/SwiftCheck/blob/swift-develop/SwiftCheck/Gen.swift#L254-L256

**Comment by zbeckman** [comment]
That's a good example – hadn't seen that one (I had been referencing the Swiftx docs, but that example is an excellent one). I'd love to see a lot of this make it's way into SwiftCheck documentation – it would make the library much more accessible. I'm persistent enough to push through it and figure it out, but I know a lot of people aren't.

**Comment by zbeckman** [comment]
Ok – trying to put together a "list of really nice to have's" for the documentation.

Here's one that I'm stuck on: How would I write a generator that takes a random element from an Array? Been reading the code... haven't figured it out yet.

**Comment by zbeckman** [comment]
Tried to find an example of a Gen that would pull a random element out of an array. Can't find one in the code (yet?)... and am having trouble coming up with a solution that feels right.

Here's what I've got. Seems like overkill, do I really need to compose two generators for this? (Once cleaned up, please add this as an example – pulling a random item from an array is a really, really useful "real world" case):
```swift
fit("returns random array entries") {
	let theArray = [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
	
	let randomSelector: Gen<Int> = Gen<Int>.fromElementsIn(0...9) >>- { item in
		return Gen.pure(theArray[item])
	}
				
	property("array items are randomly selected") <- forAll(randomSelector) { (e : Int) in
		return (e >= 0 && e <= 9)
	}
}
```

**Comment by CodaFi** [comment]
`fromElementsOf` does that already if you want selection from the whole of the array.

**Comment by zbeckman** [comment]
I thought so too, but could not get it to compile... what am I doing wrong?
```swift
it("returns random array entries") {
	let randomSelector: Gen<Int> = Gen<Int>.fromElementsIn(theArray)
				
	property("array items are randomly selected") <- forAll(randomSelector) { (e : Int) in
		return (theArray.contains(e))
	}
}
```

**Comment by CodaFi** [comment]
`Of`, not `In`.

Mnemonic: *In*dexable.

**Comment by CodaFi** [comment]
I believe with that this issue is closed.  If not, feel free to re-open it.
