### ISSUE TITLE
Range on Gen<Int> is not very wide...

### ISSUE THREAD

**Issue by zbeckman** [typelift/SwiftCheck#93]
When running a simple test (contrived):
```swift
	property("generates arbitrary Int") <- forAll { (i: Int) in
		logger.info("int \(i)")
		return i == i
	}
```
Rather surprised that the output range is from in the approximate range of -77 to 90.

I would expect to have fairly wide range over the entire size of an Int (that is, -2,147,483,648 to 2,147,483,647, at least... larger on 64 bit I think).

I know I can write my own ("ArbitraryLargeInt" or something)... but it seems to me that the default behavior should be to supply values across the native range of the type in question.

**Comment by CodaFi** [comment]
Yeah, it's not.  QuickCheck (and SwiftCheck) limit their generator to size 100.  #92 will help, but QuickCheck provides a `Large<T>` and `Small<T>` modifiers for that too that need to be implemented.

**Comment by CodaFi** [comment]
In the meantime, this will work

```swift
public struct Large<A : protocol<RandomType, LatticeType, IntegerType>> : Arbitrary {
	public let getLarge : A

	public init(_ lrg : A) {
		self.getLarge = lrg
	}

	public var description : String {
		return "Large( \(self.getLarge) )"
	}

	public static var arbitrary : Gen<Large<A>> {
		return Gen<A>.choose((A.min, A.max)).fmap(Large.init)
	}

	public static func shrink(bl : Large<A>) -> [Large<A>] {
		return bl.getLarge.shrinkIntegral.map(Large.init)
	}
}
```

**Comment by CodaFi** [comment]
Now that `Large` has been merged this issue is resolved.
