### ISSUE TITLE
Confusing swift-2.0 compiler messages

### ISSUE THREAD

**Issue by DanielAsher** [typelift/SwiftCheck#95]
`Gen` definitions often cause confusing compiler messages, e.g:

```
let attributeList : Gen<String> = 
    idStatement.proliferateNonEmpty().fmap { (s:[String]) in s.flatMap { $0 } }`
```
causes:
`Error: Cannot convert value of type 'Gen<[_Element]>' (aka 'Gen<Array<Character>>') to specified type 'Gen<String>'`

the documentation is excellent, but expanding the section handling `swift-2.0`'s quirks would be awesome!

**Comment by DanielAsher** [comment]
this works:
`let attributeList = idStatement.proliferateNonEmpty().fmap { $0.joinWithSeparator("") }`

so I can probably close this issue as down to (my) human error

**Comment by CodaFi** [comment]
Mhm.  Take your error up with Apple with a bug report, tho.  I've long known that incorrectly using this framework can cause the dumbest, most unhelpful errors to come out of Swiftc.

**Comment by CodaFi** [comment]
But as long as you have things figured out, then I'll go ahead and close this.
