### ISSUE TITLE
Consider adding `focusproperty`, similar to `Quick`'s `fit` or focused `it`

### ISSUE THREAD

**Issue by DanielAsher** [typelift/SwiftCheck#96]
quickly prepending `focus` to a `property` should work like `Quick`'s `fit`, narrowing tests run only to _focus_'ed properties.

**Comment by CodaFi** [comment]
SwiftCheck isn't a complete replacement for XCTest.  We still use Apple's mechanism to get the tests actually run.  As such this falls outside the scope of the framework.

**Comment by DanielAsher** [comment]
this makes sense. I'll try using `Quick` for that :+1:
