### ISSUE TITLE
Ambiguity?

### ISSUE THREAD

**Issue by zbeckman** [typelift/SwiftCheck#98]
Just tried the latest pull from the Swift develop branch.

This:
```
	static let username = Gen<Character>.oneOf([
		alphanumeric,
		allowedSymbols,
		latin
		]).proliferateNonEmpty().suchThat({ $0.count > 2 && $0.count < 25 }).fmap(String.init)
```
Is generating a compiler error about `Type of expression is ambiguous without more context` (but it worked as of a few days ago). Intentional change?

**Comment by CodaFi** [comment]
Some things to check:

- What is the type of `alphanumeric`, `allowedSymbols`, `line` and do they all match?
- Does adding an explicit type signature to `username` fix it or make it worse?

**Comment by zbeckman** [comment]
Here's the generators:
```
	static let upperCase: Gen<Character>= Gen<Character>.fromElementsIn("A"..."Z")
	static let lowerCase: Gen<Character> = Gen<Character>.fromElementsIn("a"..."z")
	static let digits: Gen<Character> = Gen<Character>.fromElementsIn("0"..."9")
	static let alpha: Gen<Character> = Gen<Character>.oneOf([upperCase, lowerCase])
	static let alphanumeric: Gen<Character> = Gen<Character>.oneOf([alpha, digits])
	static let latin: Gen<Character> = Gen<Character>.fromElementsIn("\u{00C0}"..."\u{02B8}")
	static let allowedSymbols = Gen<Character>.fromElementsOf(["%", "+", "-", "_", "."])
```
Adding the explicit signature on these did not help.

Now I'm getting the following errors on the composed Gen types:
```
let stringGenerator: Gen<String> = Gen<Int>.fromElementsIn(1...100) >>- { size in
	return Gen<Character>.oneOf([upper, lower, numeric, special]).proliferateSized(size).fmap(String.init)
}
/Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/GlimpulseTests/TestGenerators.swift:210:35: Type of expression is ambiguous without more context
```

```
let localEmail: Gen<String> = Gen<Character>.oneOf([
	upper,
	lower,
	numeric,
	special,
	]).proliferateNonEmpty().suchThat({ $0[$0.endIndex.predecessor()] != "." && $0.count < 15 }).fmap(String.init)
/Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/GlimpulseTests/TestGenerators.swift:224:57: Type of expression is ambiguous without more context
```

```
let hostname: Gen<String> = Gen<String>.oneOf([
	lower,
	numeric,
	Gen.pure("-"),
]).proliferateNonEmpty().suchThat({ $0.count < 10 }).fmap(String.init)
/Users/zbeckman/Projects/Glimpulse/iOS/project/Glimpulse/GlimpulseTests/TestGenerators.swift:231:46: Cannot invoke 'oneOf' with an argument list of type '([Gen<Character>])'
```

**Comment by CodaFi** [comment]
I see `upper lower numeric special` in the examples given and `upperCase lowerCase digits` in the code samples.

**Comment by CodaFi** [comment]
That last one really is user error tho.  `Gen<String>.oneOf` needs to be `Gen<Character>.oneOf`

**Comment by zbeckman** [comment]
Oops, sorry – sloppy copy-paste.

So that's interesting – Apparently the *previous* version was compiling that last one, and it worked. That might explain why things got broken! Anyhow, you must have implemented some stronger typing or something – as you point out it shouldn't have compiled.

So the error came down to that `Gen<String>` that should have been a `Gen<Character>`. All better now. Thanks!

**Comment by CodaFi** [comment]
Glad I could help.  Keep em' coming!
